version: "3.8"

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-express
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: "Express"
      MSSQL_COLLATION: ${MSSQL_COLLATION:-SQL_Latin1_General_CP1_CI_AS}
    ports:
      - "${HOST_SQL_PORT:-1433}:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433' >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s
    restart: unless-stopped

  db-init:
    image: mcr.microsoft.com/mssql-tools:latest
    depends_on:
      - sql
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      DB_NAME: ${DB_NAME}
      SQL_HOST: sql
      SQL_PORT: 1433
    volumes:
      - ./init:/init:ro
      - ./scripts:/scripts:ro
    entrypoint: ["/bin/bash", "/scripts/db-init.sh"]
    restart: "no"

volumes:
  mssql_data:
