--
-- PostgreSQL database dump
--

\restrict cCtYqwCmEEBnA1LpfvpKOtipf3IjxKyU4T4vOVkYOVC9gRG47iouDyQfnjDrAeb

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Exception; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Exception" (
    exception_id integer NOT NULL,
    company_id integer NOT NULL,
    category character varying(50),
    type character varying(100) NOT NULL,
    exception_type character varying(20) NOT NULL,
    criticity character varying(20) NOT NULL,
    description text,
    amount numeric(18,2) NOT NULL,
    sign character varying(10),
    reference_type character varying(50),
    reference character varying(100),
    reference_status character varying(50),
    odoo_link character varying(512),
    status character varying(20) NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    exclude_from_analytics boolean DEFAULT false NOT NULL,
    CONSTRAINT ck_exception_criticity CHECK (((criticity)::text = ANY ((ARRAY['Critique'::character varying, 'Majeure'::character varying, 'Warning'::character varying])::text[]))),
    CONSTRAINT ck_exception_exception_type CHECK (((exception_type)::text = ANY ((ARRAY['Auto'::character varying, 'À ajouter'::character varying, 'Partiel'::character varying])::text[]))),
    CONSTRAINT ck_exception_status CHECK (((status)::text = ANY ((ARRAY['Actif'::character varying, 'Désactivé'::character varying])::text[])))
);


--
-- Name: Exception_exception_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Exception" ALTER COLUMN exception_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Exception_exception_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: User; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."User" (
    user_id integer NOT NULL,
    display_name character varying(120) NOT NULL,
    email character varying(254) NOT NULL,
    role character varying(20) NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    password_hash character varying(255),
    CONSTRAINT ck_user_role CHECK (((role)::text = ANY ((ARRAY['Admin'::character varying, 'Manager'::character varying])::text[])))
);


--
-- Name: User_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."User" ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company (
    company_id integer NOT NULL,
    name character varying(200) NOT NULL
);


--
-- Name: company_company_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company ALTER COLUMN company_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: data_refresh_execution; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.data_refresh_execution (
    execution_id integer NOT NULL,
    status character varying(20) NOT NULL,
    started_by integer NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    duration_seconds integer,
    total_records_processed integer DEFAULT 0,
    error_message text,
    progress_percentage integer DEFAULT 0,
    current_step character varying(100),
    details jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT data_refresh_execution_progress_percentage_check CHECK (((progress_percentage >= 0) AND (progress_percentage <= 100))),
    CONSTRAINT data_refresh_execution_status_check CHECK (((status)::text = ANY ((ARRAY['running'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying])::text[])))
);


--
-- Name: TABLE data_refresh_execution; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.data_refresh_execution IS 'Tracks data refresh operations from Odoo. Used to prevent concurrent refreshes and show history.';


--
-- Name: COLUMN data_refresh_execution.status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.data_refresh_execution.status IS 'Current status: running, completed, failed, or cancelled';


--
-- Name: COLUMN data_refresh_execution.progress_percentage; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.data_refresh_execution.progress_percentage IS 'Current progress from 0 to 100';


--
-- Name: COLUMN data_refresh_execution.current_step; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.data_refresh_execution.current_step IS 'Human-readable description of current operation';


--
-- Name: COLUMN data_refresh_execution.details; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.data_refresh_execution.details IS 'JSON details about each job (purchases, sales, etc.)';


--
-- Name: data_refresh_execution_execution_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.data_refresh_execution_execution_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: data_refresh_execution_execution_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.data_refresh_execution_execution_id_seq OWNED BY public.data_refresh_execution.execution_id;


--
-- Name: manual_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.manual_entry (
    manual_entry_id integer NOT NULL,
    frequency character varying(20) NOT NULL,
    start_date date NOT NULL,
    timezone character varying(64),
    recurrence jsonb,
    rrule character varying(512),
    metadata jsonb,
    end_date date,
    created_by integer NOT NULL,
    CONSTRAINT ck_manualentry_frequency CHECK (((frequency)::text = ANY ((ARRAY['Une seule fois'::character varying, 'Mensuel'::character varying, 'Annuel'::character varying, 'Dates personnalisées'::character varying])::text[])))
);


--
-- Name: COLUMN manual_entry.created_by; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.manual_entry.created_by IS 'User who created this manual entry - used for own_data_only permission filtering';


--
-- Name: manual_entry_manual_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.manual_entry ALTER COLUMN manual_entry_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.manual_entry_manual_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movement (
    movement_id integer NOT NULL,
    company_id integer NOT NULL,
    manual_entry_id integer,
    category character varying(20) NOT NULL,
    type character varying(100) NOT NULL,
    amount numeric(18,2) NOT NULL,
    sign character varying(10) NOT NULL,
    movement_date date NOT NULL,
    reference_type character varying(50) NOT NULL,
    reference character varying(100) NOT NULL,
    reference_status character varying(50),
    source character varying(30) NOT NULL,
    note text,
    status character varying(20) NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    created_by integer NOT NULL,
    odoo_link character varying(512),
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    updated_by integer,
    disabled_at timestamp(3) with time zone,
    disabled_by integer,
    disable_reason text,
    archived_at timestamp(3) with time zone,
    archived_by integer,
    archive_reason text,
    archive_version integer DEFAULT 1 NOT NULL,
    exchange_rate numeric(18,6),
    exclude_from_analytics boolean DEFAULT false NOT NULL,
    CONSTRAINT ck_movement_amount_nonnegative CHECK ((amount >= (0)::numeric)),
    CONSTRAINT ck_movement_category CHECK (((category)::text = ANY ((ARRAY['RH'::character varying, 'Achat'::character varying, 'Vente'::character varying, 'Compta'::character varying, 'Autre'::character varying])::text[]))),
    CONSTRAINT ck_movement_reference_type CHECK (((reference_type)::text = ANY ((ARRAY['Facture'::character varying, 'Avoir'::character varying, 'BL'::character varying, 'Cmd CLI/Fourn.'::character varying])::text[]))),
    CONSTRAINT ck_movement_sign CHECK (((sign)::text = ANY ((ARRAY['Entrée'::character varying, 'Sortie'::character varying])::text[]))),
    CONSTRAINT ck_movement_source CHECK (((source)::text = ANY ((ARRAY['Odoo'::character varying, 'Entrée manuelle'::character varying])::text[]))),
    CONSTRAINT ck_movement_status CHECK (((status)::text = ANY ((ARRAY['Actif'::character varying, 'Désactivé'::character varying, 'Archivé'::character varying])::text[])))
);


--
-- Name: COLUMN movement.exchange_rate; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.movement.exchange_rate IS 'Taux de change pour les achats d''importation (custom_rate depuis Odoo account.move)';


--
-- Name: COLUMN movement.exclude_from_analytics; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.movement.exclude_from_analytics IS 'When true, this movement is excluded from all analytics and projections';


--
-- Name: movement_movement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.movement ALTER COLUMN movement_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movement_movement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supervision_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.supervision_log (
    log_id integer NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer,
    action character varying(50) NOT NULL,
    user_id integer NOT NULL,
    user_name character varying(120) NOT NULL,
    "timestamp" timestamp(3) with time zone DEFAULT now() NOT NULL,
    details json,
    description text,
    company_id integer,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_supervision_action CHECK (((action)::text = ANY ((ARRAY['include'::character varying, 'exclude'::character varying, 'insert'::character varying, 'update'::character varying, 'delete'::character varying, 'refresh'::character varying, 'create'::character varying, 'modify'::character varying])::text[]))),
    CONSTRAINT ck_supervision_entity_type CHECK (((entity_type)::text = ANY ((ARRAY['movement'::character varying, 'manual_entry'::character varying, 'data_refresh'::character varying])::text[])))
);


--
-- Name: supervision_log_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.supervision_log_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: supervision_log_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.supervision_log_log_id_seq OWNED BY public.supervision_log.log_id;


--
-- Name: tab_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tab_permissions (
    tab_id integer NOT NULL,
    tab_name character varying(50) NOT NULL,
    tab_label character varying(100) NOT NULL,
    description text,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);


--
-- Name: tab_permissions_tab_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tab_permissions_tab_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tab_permissions_tab_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tab_permissions_tab_id_seq OWNED BY public.tab_permissions.tab_id;


--
-- Name: treasury_balance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.treasury_balance (
    treasury_balance_id integer NOT NULL,
    company_id integer NOT NULL,
    amount numeric(18,2) NOT NULL,
    reference_date date NOT NULL,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    updated_by integer NOT NULL,
    notes text,
    CONSTRAINT ck_treasurybalance_amount_positive CHECK ((amount >= (0)::numeric))
);


--
-- Name: TABLE treasury_balance; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.treasury_balance IS 'Stores the reference treasury balance (bank accounts + cash) for each company at a specific date. This is the baseline for all treasury calculations and forecasts.';


--
-- Name: COLUMN treasury_balance.amount; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.treasury_balance.amount IS 'Total treasury amount in EUR (sum of all bank accounts and cash)';


--
-- Name: COLUMN treasury_balance.reference_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.treasury_balance.reference_date IS 'Date when this balance was recorded. The most recent date for each company is considered the current reference.';


--
-- Name: COLUMN treasury_balance.notes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.treasury_balance.notes IS 'Optional notes about this balance entry (e.g., which accounts were included)';


--
-- Name: treasury_balance_source; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.treasury_balance_source (
    source_id integer NOT NULL,
    treasury_balance_id integer NOT NULL,
    source_name character varying(255) NOT NULL,
    amount numeric(18,2) NOT NULL,
    source_date date NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE treasury_balance_source; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.treasury_balance_source IS 'Stores individual sources (bank accounts, cash, etc.) that make up a treasury balance';


--
-- Name: COLUMN treasury_balance_source.source_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.treasury_balance_source.source_name IS 'Name of the source (e.g., BNP Account, Cash, Crédit Agricole)';


--
-- Name: COLUMN treasury_balance_source.amount; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.treasury_balance_source.amount IS 'Amount for this specific source';


--
-- Name: COLUMN treasury_balance_source.source_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.treasury_balance_source.source_date IS 'Date when this specific source balance was checked';


--
-- Name: treasury_balance_source_source_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.treasury_balance_source_source_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: treasury_balance_source_source_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.treasury_balance_source_source_id_seq OWNED BY public.treasury_balance_source.source_id;


--
-- Name: treasury_balance_treasury_balance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.treasury_balance ALTER COLUMN treasury_balance_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.treasury_balance_treasury_balance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_company; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_company (
    user_company_id integer NOT NULL,
    user_id integer NOT NULL,
    company_id integer NOT NULL
);


--
-- Name: user_company_user_company_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_company ALTER COLUMN user_company_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_company_user_company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_tab_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_tab_permissions (
    user_tab_permission_id integer NOT NULL,
    user_id integer NOT NULL,
    tab_id integer NOT NULL,
    can_view boolean DEFAULT false NOT NULL,
    can_modify boolean DEFAULT false NOT NULL,
    created_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
    own_data_only boolean DEFAULT false NOT NULL,
    allowed_categories jsonb
);


--
-- Name: COLUMN user_tab_permissions.own_data_only; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.user_tab_permissions.own_data_only IS 'If true, user can only see/modify data they created (for movements and manual-entries)';


--
-- Name: user_tab_permissions_user_tab_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_tab_permissions_user_tab_permission_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_tab_permissions_user_tab_permission_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_tab_permissions_user_tab_permission_id_seq OWNED BY public.user_tab_permissions.user_tab_permission_id;


--
-- Name: data_refresh_execution execution_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_refresh_execution ALTER COLUMN execution_id SET DEFAULT nextval('public.data_refresh_execution_execution_id_seq'::regclass);


--
-- Name: supervision_log log_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supervision_log ALTER COLUMN log_id SET DEFAULT nextval('public.supervision_log_log_id_seq'::regclass);


--
-- Name: tab_permissions tab_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tab_permissions ALTER COLUMN tab_id SET DEFAULT nextval('public.tab_permissions_tab_id_seq'::regclass);


--
-- Name: treasury_balance_source source_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.treasury_balance_source ALTER COLUMN source_id SET DEFAULT nextval('public.treasury_balance_source_source_id_seq'::regclass);


--
-- Name: user_tab_permissions user_tab_permission_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_tab_permissions ALTER COLUMN user_tab_permission_id SET DEFAULT nextval('public.user_tab_permissions_user_tab_permission_id_seq'::regclass);


--
-- Name: Exception Exception_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Exception"
    ADD CONSTRAINT "Exception_pkey" PRIMARY KEY (exception_id);


--
-- Name: User User_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_pkey" PRIMARY KEY (user_id);


--
-- Name: company company_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_pkey PRIMARY KEY (company_id);


--
-- Name: data_refresh_execution data_refresh_execution_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_refresh_execution
    ADD CONSTRAINT data_refresh_execution_pkey PRIMARY KEY (execution_id);


--
-- Name: manual_entry manual_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.manual_entry
    ADD CONSTRAINT manual_entry_pkey PRIMARY KEY (manual_entry_id);


--
-- Name: movement movement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT movement_pkey PRIMARY KEY (movement_id);


--
-- Name: supervision_log supervision_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supervision_log
    ADD CONSTRAINT supervision_log_pkey PRIMARY KEY (log_id);


--
-- Name: tab_permissions tab_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tab_permissions
    ADD CONSTRAINT tab_permissions_pkey PRIMARY KEY (tab_id);


--
-- Name: tab_permissions tab_permissions_tab_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tab_permissions
    ADD CONSTRAINT tab_permissions_tab_name_key UNIQUE (tab_name);


--
-- Name: treasury_balance treasury_balance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.treasury_balance
    ADD CONSTRAINT treasury_balance_pkey PRIMARY KEY (treasury_balance_id);


--
-- Name: treasury_balance_source treasury_balance_source_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.treasury_balance_source
    ADD CONSTRAINT treasury_balance_source_pkey PRIMARY KEY (source_id);


--
-- Name: user_company user_company_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_company
    ADD CONSTRAINT user_company_pkey PRIMARY KEY (user_company_id);


--
-- Name: user_tab_permissions user_tab_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_tab_permissions
    ADD CONSTRAINT user_tab_permissions_pkey PRIMARY KEY (user_tab_permission_id);


--
-- Name: user_company ux_user_company_user_company; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_company
    ADD CONSTRAINT ux_user_company_user_company UNIQUE (user_id, company_id);


--
-- Name: User ux_user_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT ux_user_email UNIQUE (email);


--
-- Name: user_tab_permissions ux_user_tab_permissions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_tab_permissions
    ADD CONSTRAINT ux_user_tab_permissions UNIQUE (user_id, tab_id);


--
-- Name: idx_user_tab_permissions_allowed_categories; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_tab_permissions_allowed_categories ON public.user_tab_permissions USING gin (allowed_categories);


--
-- Name: ix_data_refresh_execution_started_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_data_refresh_execution_started_at ON public.data_refresh_execution USING btree (started_at DESC);


--
-- Name: ix_data_refresh_execution_started_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_data_refresh_execution_started_by ON public.data_refresh_execution USING btree (started_by);


--
-- Name: ix_data_refresh_execution_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_data_refresh_execution_status ON public.data_refresh_execution USING btree (status);


--
-- Name: ix_exception_exclude_analytics; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_exception_exclude_analytics ON public."Exception" USING btree (exclude_from_analytics) WHERE (exclude_from_analytics = false);


--
-- Name: ix_manual_entry_created_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_manual_entry_created_by ON public.manual_entry USING btree (created_by);


--
-- Name: ix_movement_archived_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_movement_archived_by ON public.movement USING btree (archived_by);


--
-- Name: ix_movement_company; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_movement_company ON public.movement USING btree (company_id);


--
-- Name: ix_movement_company_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_movement_company_date ON public.movement USING btree (company_id, movement_date);


--
-- Name: ix_movement_created_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_movement_created_by ON public.movement USING btree (created_by);


--
-- Name: ix_movement_disabled_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_movement_disabled_by ON public.movement USING btree (disabled_by);


--
-- Name: ix_movement_exclude_analytics; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_movement_exclude_analytics ON public.movement USING btree (exclude_from_analytics) WHERE (exclude_from_analytics = false);


--
-- Name: ix_movement_updated_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_movement_updated_by ON public.movement USING btree (updated_by);


--
-- Name: ix_supervision_log_action; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_supervision_log_action ON public.supervision_log USING btree (action);


--
-- Name: ix_supervision_log_company; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_supervision_log_company ON public.supervision_log USING btree (company_id);


--
-- Name: ix_supervision_log_entity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_supervision_log_entity ON public.supervision_log USING btree (entity_type, entity_id);


--
-- Name: ix_supervision_log_timestamp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_supervision_log_timestamp ON public.supervision_log USING btree ("timestamp" DESC);


--
-- Name: ix_supervision_log_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_supervision_log_user ON public.supervision_log USING btree (user_id);


--
-- Name: ix_treasurybalance_company; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_treasurybalance_company ON public.treasury_balance USING btree (company_id);


--
-- Name: ix_treasurybalance_updated_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_treasurybalance_updated_by ON public.treasury_balance USING btree (updated_by);


--
-- Name: ix_treasurybalancesource_treasury; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_treasurybalancesource_treasury ON public.treasury_balance_source USING btree (treasury_balance_id);


--
-- Name: ix_user_tab_permissions_tab; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_tab_permissions_tab ON public.user_tab_permissions USING btree (tab_id);


--
-- Name: ix_user_tab_permissions_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_tab_permissions_user ON public.user_tab_permissions USING btree (user_id);


--
-- Name: ux_movement_reference; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_movement_reference ON public.movement USING btree (company_id, reference_type, reference, archive_version);


--
-- Name: ux_treasurybalance_company_date; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_treasurybalance_company_date ON public.treasury_balance USING btree (company_id, reference_date);


--
-- Name: Exception Exception_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Exception"
    ADD CONSTRAINT "Exception_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public.company(company_id);


--
-- Name: data_refresh_execution data_refresh_execution_started_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_refresh_execution
    ADD CONSTRAINT data_refresh_execution_started_by_fkey FOREIGN KEY (started_by) REFERENCES public."User"(user_id);


--
-- Name: treasury_balance_source fk_treasurybalancesource_treasurybalance; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.treasury_balance_source
    ADD CONSTRAINT fk_treasurybalancesource_treasurybalance FOREIGN KEY (treasury_balance_id) REFERENCES public.treasury_balance(treasury_balance_id) ON DELETE CASCADE;


--
-- Name: manual_entry manual_entry_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.manual_entry
    ADD CONSTRAINT manual_entry_created_by_fkey FOREIGN KEY (created_by) REFERENCES public."User"(user_id);


--
-- Name: movement movement_archived_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT movement_archived_by_fkey FOREIGN KEY (archived_by) REFERENCES public."User"(user_id);


--
-- Name: movement movement_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT movement_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.company(company_id);


--
-- Name: movement movement_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT movement_created_by_fkey FOREIGN KEY (created_by) REFERENCES public."User"(user_id);


--
-- Name: movement movement_disabled_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT movement_disabled_by_fkey FOREIGN KEY (disabled_by) REFERENCES public."User"(user_id);


--
-- Name: movement movement_manual_entry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT movement_manual_entry_id_fkey FOREIGN KEY (manual_entry_id) REFERENCES public.manual_entry(manual_entry_id);


--
-- Name: movement movement_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT movement_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public."User"(user_id);


--
-- Name: supervision_log supervision_log_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supervision_log
    ADD CONSTRAINT supervision_log_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.company(company_id) ON DELETE SET NULL;


--
-- Name: supervision_log supervision_log_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supervision_log
    ADD CONSTRAINT supervision_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."User"(user_id) ON DELETE CASCADE;


--
-- Name: treasury_balance treasury_balance_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.treasury_balance
    ADD CONSTRAINT treasury_balance_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.company(company_id);


--
-- Name: treasury_balance treasury_balance_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.treasury_balance
    ADD CONSTRAINT treasury_balance_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public."User"(user_id);


--
-- Name: user_company user_company_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_company
    ADD CONSTRAINT user_company_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.company(company_id);


--
-- Name: user_company user_company_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_company
    ADD CONSTRAINT user_company_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."User"(user_id);


--
-- Name: user_tab_permissions user_tab_permissions_tab_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_tab_permissions
    ADD CONSTRAINT user_tab_permissions_tab_id_fkey FOREIGN KEY (tab_id) REFERENCES public.tab_permissions(tab_id) ON DELETE CASCADE;


--
-- Name: user_tab_permissions user_tab_permissions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_tab_permissions
    ADD CONSTRAINT user_tab_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."User"(user_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict cCtYqwCmEEBnA1LpfvpKOtipf3IjxKyU4T4vOVkYOVC9gRG47iouDyQfnjDrAeb

