-- Add Treasury Balance table
-- This table stores the reference treasury balance for each company at a specific date
-- This is the baseline used to calculate current and predicted balances

BEGIN;

CREATE TABLE IF NOT EXISTS Treasury_Balance (
  treasury_balance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id          INTEGER         NOT NULL REFERENCES Company(company_id),
  amount              NUMERIC(18,2)   NOT NULL,
  reference_date      DATE            NOT NULL,
  updated_at          TIMESTAMPTZ(3)  NOT NULL DEFAULT now(),
  updated_by          INTEGER         NOT NULL REFERENCES "User"(user_id),
  notes               TEXT,
  CONSTRAINT CK_TreasuryBalance_amount_positive CHECK (amount >= 0)
);

-- Only one active balance per company (latest reference_date is considered active)
CREATE UNIQUE INDEX IF NOT EXISTS UX_TreasuryBalance_company ON Treasury_Balance(company_id, reference_date DESC);

-- Index for quick company lookups
CREATE INDEX IF NOT EXISTS IX_TreasuryBalance_company ON Treasury_Balance(company_id);
CREATE INDEX IF NOT EXISTS IX_TreasuryBalance_updated_by ON Treasury_Balance(updated_by);

COMMENT ON TABLE Treasury_Balance IS 'Stores the reference treasury balance (bank accounts + cash) for each company at a specific date. This is the baseline for all treasury calculations and forecasts.';
COMMENT ON COLUMN Treasury_Balance.amount IS 'Total treasury amount in EUR (sum of all bank accounts and cash)';
COMMENT ON COLUMN Treasury_Balance.reference_date IS 'Date when this balance was recorded. The most recent date for each company is considered the current reference.';
COMMENT ON COLUMN Treasury_Balance.notes IS 'Optional notes about this balance entry (e.g., which accounts were included)';

COMMIT;
